name: 🐛 Bug report
description: Create a report to help us improve
labels: [bug]
body:
  - type: markdown
    attributes:
      value: |
        Thank you for reporting an issue.

        This issue tracker is for bugs and issues found within the project.

        Please fill in as much of the following form as you're able.
  - type: input
    attributes:
      label: Version 
    validations:
      required: true
  - type: input
    attributes:
      label: Platform
      description: |
        UNIX: output of `uname -a`
        Windows: output of `"$([Environment]::OSVersion.VersionString) $(('x86', 'x64')[[Environment]::Is64BitOperatingSystem])"` in PowerShell console
    validations:
      required: true
  - type: dropdown
    attributes:
      label: Does the issue appear inside the browser, inside node, or both?
      multiple: true
      options:
        - Browser
        - Node
    validations:
      required: true
  - type: textarea
    attributes:
      label: What steps will reproduce the bug?
      description: Enter details about your bug, preferably a simple code snippet that can be run within a browser, or using node directly without installing third-party dependencies.
  - type: textarea
    attributes:
      label: How often does it reproduce? Is there a required condition?
    validations:
      required: true
  - type: textarea
    attributes:
      label: What is the expected behavior? What do you see instead?
      description: If possible please provide textual output instead of screenshots.
    validations:
      required: true
